logging:
  level:
    root: INFO
    net.smilfinken: INFO

application:
  info:
    name: ${name:Connected Meter}
    version: ${version:0.0.0}
  schedule.cron: 1 0 * * * *
  format:
    datePattern: YYYY-MM-dd
    timePattern: HH:mm:ss
  chart:
    daily:
      daysToShow: 30
    hourly:
      hoursToShow: 24
    monthly:
      monthsToShow: 12
  statistics:
    daily:
      daysToShow: 7
  keys:
    energy:
      incoming: 1-0:1.7.0
      outgoing: 1-0:2.7.0
    temperature:
      indoor: FIBARO_INDOOR
      outdoor: FIBARO_OUTDOOR
  api:
    inverter:
      baseUri: http://fronius.smilfinken.net/solar_api/v1
      realtimeDataPath: GetInverterRealtimeData.cgi?Scope=System
      archiveDataPath: GetArchiveData.cgi?Scope=System&Channel=EnergyReal_WAC_Sum_Produced&SeriesType=DailySum
      startDateQueryParameter: StartDate
      endDateQueryParameter: EndDate
      datePattern: YYYY-MM-dd
