spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  h2:
    console.enabled: true

logging:
  level:
    root: INFO
    net.smilfinken: INFO
    net.smilfinken.meter.collector: DEBUG