spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  h2.console.enabled: true
  jpa.show-sql: false

logging:
  level:
    net.smilfinken.meter.collector: TRACE
