alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists daily_data cascade;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists monthly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists daily_data cascade;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists monthly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
alter table if exists data_item drop constraint if exists FKm78wx5m46syf4nc7prr9dqen;
alter table if exists power_output drop constraint if exists FK4o366vob6angad7tfjtlmsvcx;
alter table if exists temperature drop constraint if exists FKcb1ckunp1sretk4g9u6suj2ic;
drop table if exists data_item cascade;
drop table if exists data_report cascade;
drop table if exists hourly_data cascade;
drop table if exists power_output cascade;
drop table if exists temperature cascade;
